import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/sidebar'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className='grid min-h-screen bg-white font-sans dark:bg-black [grid-template-areas:"header_header_header_header_right"_"sidebar_main_main_main_right"_"sidebar_main_main_main_right"_"sidebar_main_main_main_right"_"footer_footer_footer_footer_right"]  auto-rows-fr auto-cols-fr'>
					<header className='[grid-area:header] border-b border-b-white/10 w-full h-full'>
						header
					</header>
					<Sidebar />
					<main className='[grid-area:main] w-full h-full p-4'>{children}</main>
					<aside className='[grid-area:right] border-l border-l-white/10 w-full h-full '>
						right
					</aside>
					<footer className='[grid-area:footer] border-t border-t-white/10 w-full h-full'>
						footer
					</footer>
				</div>
			</body>
		</html>
	)
}
